version: "3.8"

services:
  backend:
    image: "${BACKEND_IMAGE:-gulamgaush/fusionpact-backend:latest}"
    container_name: fusionpact_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - backend_logs:/var/log/fusionpact
    healthcheck:
      test: ["CMD-SHELL", "curl -fS http://localhost:8000/health || curl -fS http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - fp-net

  frontend:
    image: "${FRONTEND_IMAGE:-gulamgaush/fusionpact-frontend:latest}"
    container_name: fusionpact_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -fS http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - fp-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - fp-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "472"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - fp-net

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - fp-net

networks:
  fp-net:
    driver: bridge

volumes:
  backend_logs:
  prometheus_data:
  grafana_data:
