version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fusionpact_backend
    restart: unless-stopped
    volumes:
      - backend_data:/app/app/data
    ports:
      - "8000:8000"    # public backend port
    networks:
      - fusionnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fusionpact_frontend
    restart: unless-stopped
    ports:
      - "80:80"        # public frontend port
    networks:
      - fusionnet

  prometheus:
    image: prom/prometheus:latest
    container_name: fusionpact_prometheus
    volumes:
      - ./monitoring:/etc/prometheus:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - fusionnet

  grafana:
    image: grafana/grafana:latest
    container_name: fusionpact_grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-polystat-panel
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - fusionnet


networks:
  fusionnet:
    driver: bridge

volumes:
  backend_data:
  prometheus_data:
  grafana_data:
