global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['backend:8000']   # scrape FastAPI /metrics


  # (optional) scrape prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
