global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['backend:8000']   # scrape FastAPI /metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # (optional) scrape prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
